console.log("%c1.- Ejercicio 02: tipos de datos",style_console);


console.warn("1.- UNDEFINED (No Definido )")
let usuarioLogeado;
var rolUsuario;
const ultimoAcceso = undefined;

console.log("Valores actuales de dos variables ");
console.log('usuarioLogeado =${usuarioLogeado}');
console.log('rolUsuario =${rolUsuario}');
console.log('ultimoAcceso =${ultimoAcceso}');
        
console.log("Valores actuales de las variables ");
console.log('usuarioLogeado =${typeof{usuarioLogeado}}');
console.log('rolUsuario =${typeof{rolUsuario}}');
console.log('ultimoAcceso =${typeof{ultimoAcceso}}');

usuarioLogeado = "JuanCarlos"

console.log('El valor de la variable usuarioLogeadoes: ${usuarioLogeado} y su nuevo tipo de dato es : ${typeof{usuarioLogeado}')